# BSEACD In-House Recharge CSV Generator
Script for generating Recharge CSV for direct import into Vistas; outputs CSV with columns: node/SP/recharge value (ft/d)

Todo-incorporate geopandas functions to do geoprossessing (spatial joining rch zones and model grid) outside of arcmap

In [2]:
import pandas as pd
import numpy as np

In [5]:
#Specify recharged coefficients for each recharge zone
zone1=[0.01, 0.03]
zone2=[0.005, 0.01]
zone3=[0.005, 0.05]
zone4=[0.01, 0.2]
zone5=[0.001, 0.02]
zone6=[0.01, 0.15]

In [6]:
flow=pd.read_csv('Blancoflow.csv')
#import Blanco river flow (monthly average) in units of ft3/s; CSV must have 3 columns: Date/SP/BLAflow

In [7]:
flow

       Date   SP    BLAflow
0        SS    1  58.316667
1     8-Jan    2  58.316667
2     8-Feb    3  53.265517
3     8-Mar    4  49.470968
4     8-Apr    5  38.993333
..      ...  ...        ...
152  20-Aug  153  21.287097
153  20-Sep  154  32.906667
154  20-Oct  155  20.258065
155  20-Nov  156  15.866667
156  20-Dec  157  13.993548

[157 rows x 3 columns]

In [8]:
ppt=pd.read_csv('PRISM_ft-d.csv')
pptx=ppt.set_index('GridID')
pptx
#import PRISM precipitation data (monthly) in units of ft/d; creat df "pptx" with GridID specified as index; 1st CSV column must have prism GRIDID; than each subsequent column recharge values for each stress period

,SP1,SP2,SP3,SP4,SP5,SP6,SP7,SP8,SP9,SP10,...,SP148,SP149,SP150,SP151,SP152,SP153,SP154,SP155,SP156,SP157
GridID,,,,,,,,,,,,,,,,,,,,,
648347,0.000784,0.000784,0.000186,0.006980,0.005490,0.010134,1.300525e-03,0.001372,0.005234,0.000207,...,0.011042,0.010948,0.011477,0.003282,0.002304,0.004107,0.012321,0.000705,0.001752,0.002237
649751,0.000889,0.000889,0.000206,0.007619,0.008052,0.009981,9.768150e-04,0.001623,0.005896,0.000197,...,0.010165,0.010073,0.011451,0.003248,0.002212,0.003592,0.014469,0.000662,0.001631,0.002111
649752,0.001015,0.001015,0.000201,0.008484,0.007803,0.010547,1.053806e-03,0.001532,0.005705,0.000173,...,0.009846,0.010765,0.010955,0.002918,0.001726,0.003885,0.012542,0.000614,0.001597,0.002076
649753,0.001357,0.001357,0.000233,0.009461,0.007663,0.011684,1.205271e-03,0.001712,0.005871,0.000490,...,0.009393,0.011902,0.010421,0.002964,0.001689,0.004033,0.012859,0.000642,0.001694,0.002802
651154,0.000863,0.000863,0.000242,0.007317,0.010014,0.009142,9.190730e-04,0.002784,0.005855,0.000081,...,0.011119,0.009639,0.015455,0.004028,0.000855,0.003859,0.019051,0.000959,0.001837,0.002536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689093,0.001861,0.001861,0.000783,0.004086,0.005840,0.002677,2.723100e-05,0.011798,0.014021,0.002285,...,0.006320,0.007895,0.015758,0.003261,0.001498,0.004258,0.010717,0.000266,0.004236,0.002215
689094,0.002098,0.002098,0.000910,0.004648,0.005316,0.002133,1.093610e-07,0.010358,0.013097,0.002235,...,0.007279,0.007864,0.015394,0.003129,0.001669,0.003290,0.010787,0.000293,0.004296,0.002032
689095,0.002350,0.002350,0.001008,0.005045,0.005569,0.002555,0.000000e+00,0.010387,0.015866,0.002266,...,0.007950,0.007712,0.015985,0.002262,0.001872,0.002621,0.010480,0.000270,0.004165,0.002154
690498,0.001930,0.001930,0.000732,0.004632,0.005806,0.003097,1.161420e-04,0.010432,0.014956,0.001367,...,0.007032,0.007374,0.016709,0.003233,0.002027,0.004148,0.010063,0.000264,0.004638,0.002019
690499,0.002135,0.002135,0.000743,0.005272,0.005443,0.002537,2.482500e-05,0.011162,0.014792,0.001767,...,0.007831,0.007236,0.015513,0.002815,0.001807,0.003666,0.011317,0.000244,0.004621,0.001920

In [9]:
nodes=pd.read_csv('Rechargedomain_spatialjoin.csv')
#import table containing entries for every recharge node within the recharge domain and fields for recharge zone and PRISM gridID

In [10]:
nodes['GridID']=nodes['GridID'].apply(np.int64)
nodes.set_index('GridID')
nodes

         FID  Join_Count  TARGET_FID  row  column   node  GridID  Rchzone
0          0           1           0  156     143  35018  670832        1
1          1           1           1  192     146  43121  673641        5
2          2           3           2  166     117  37242  669425        1
3          3           1           3  171     118  38368  670830        4
4          4           1           4  176      39  39414  668014        2
...      ...         ...         ...  ...     ...    ...     ...      ...
11914  11914           2       11914  180     135  40410  672236        5
11915  11915           2       11915  206      45  46170  670823        2
11916  11916           1       11916  165     144  37044  670832        5
11917  11917           2       11917  153      73  34273  668017        3
11918  11918           1       11918  107     112  23962  665211        3

[11919 rows x 8 columns]

In [11]:
a=len(flow)
b=a-1
#defines array with number of stress periods from blanco river flow array

In [12]:
d=np.arange(1,a+1)
#create increasing integer array with entry for each stress period

In [13]:
c=len(nodes.node)
#defines array with number of nodes in recharge domain

In [14]:
x=nodes.set_index('GridID')
df1=x
df2=pptx
df3=pd.merge(df1,df2,left_index=True,right_index=True)
#Merge ppt and nodes dataset into new dataset called 'df3'
#for df3.iloc[:,7] now need to apply conditions to created 
    #if flow.BLAflow[0] > 40

In [15]:
#for loop apply recharge coefficients to recharge dataframe; 
for i in flow.index:
    for j in range(len(df3)):
        if df3.Rchzone.iloc[j] == 2:   
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone2[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone2[0]
        if df3.Rchzone.iloc[j] == 1:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone1[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone1[0]
        if df3.Rchzone.iloc[j] == 3:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone3[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone3[0]
        if df3.Rchzone.iloc[j] == 5:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone5[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone5[0]     
        if df3.Rchzone.iloc[j] == 6:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone6[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone6[0]  
        if df3.Rchzone.iloc[j] == 4:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone4[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone4[0]

In [16]:
df3

,FID,Join_Count,TARGET_FID,row,column,node,Rchzone,SP1,SP2,SP3,...,SP148,SP149,SP150,SP151,SP152,SP153,SP154,SP155,SP156,SP157
GridID,,,,,,,,,,,,,,,,,,,,,
665209,220,1,220,120,89,26864,3,0.000082,0.000082,0.000018,...,0.000032,0.000057,0.000747,0.000177,5.627170e-06,0.000018,0.000099,3.360215e-06,0.000017,0.000018
665209,229,1,229,125,91,27991,3,0.000082,0.000082,0.000018,...,0.000032,0.000057,0.000747,0.000177,5.627170e-06,0.000018,0.000099,3.360215e-06,0.000017,0.000018
665209,507,1,507,121,92,27092,3,0.000082,0.000082,0.000018,...,0.000032,0.000057,0.000747,0.000177,5.627170e-06,0.000018,0.000099,3.360215e-06,0.000017,0.000018
665209,1177,1,1177,126,91,28216,3,0.000082,0.000082,0.000018,...,0.000032,0.000057,0.000747,0.000177,5.627170e-06,0.000018,0.000099,3.360215e-06,0.000017,0.000018
665209,1497,1,1497,122,92,27317,3,0.000082,0.000082,0.000018,...,0.000032,0.000057,0.000747,0.000177,5.627170e-06,0.000018,0.000099,3.360215e-06,0.000017,0.000018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675046,10640,2,10640,201,152,45152,5,0.000040,0.000040,0.000014,...,0.000008,0.000012,0.000550,0.000050,7.763950e-07,0.000007,0.000017,4.330710e-07,0.000003,0.000004
675046,10826,2,10826,201,150,45150,5,0.000040,0.000040,0.000014,...,0.000008,0.000012,0.000550,0.000050,7.763950e-07,0.000007,0.000017,4.330710e-07,0.000003,0.000004
675046,11757,1,11757,202,154,45379,5,0.000040,0.000040,0.000014,...,0.000008,0.000012,0.000550,0.000050,7.763950e-07,0.000007,0.000017,4.330710e-07,0.000003,0.000004
675046,11769,2,11769,200,155,44930,5,0.000040,0.000040,0.000014,...,0.000008,0.000012,0.000550,0.000050,7.763950e-07,0.000007,0.000017,4.330710e-07,0.000003,0.000004
675047,11850,3,11850,198,157,44482,5,0.000041,0.000041,0.000016,...,0.000009,0.000013,0.000570,0.000057,7.444330e-07,0.000008,0.000018,5.816610e-07,0.000003,0.000005

In [17]:
a=df3.iloc[0,7:7+len(flow)]
a
#b=df3.iloc[:,8]
#pd.concat([a,b])

SP1      0.000082
SP2      0.000082
SP3      0.000018
SP4      0.000437
SP5      0.000021
           ...
SP153    0.000018
SP154    0.000099
SP155    0.000003
SP156    0.000017
SP157    0.000018
Name: 665209, Length: 157, dtype: float64

In [18]:
#Build new dataframe for final vistas import with 3 columns: node/SP/recharge
#dfimp=pd.DataFrame()
impNode=df3['node'].repeat(len(flow))
impSP=flow['SP']
impSP=pd.concat([impSP]*len(df3))
#Build Recharge column using concat
impRch=df3.iloc[0,7:7+len(flow)]
for i in range((len(df3)-1)):
    impRch=pd.concat([impRch,df3.iloc[i+1,7:7+len(flow)]])

#imprch=

In [19]:
impRch

SP1      8.221680e-05
SP2      8.221680e-05
SP3      1.833310e-05
SP4      4.367063e-04
SP5      2.055118e-05
             ...
SP153    7.994560e-06
SP154    1.828401e-05
SP155    5.816610e-07
SP156    3.002406e-06
SP157    4.529570e-06
Length: 1871283, dtype: float64

In [23]:
#aa=pd.concat([impNode,impSP,impRch],axis=1,ignore_index=True)
#aa=([impNode,impSP,impRch])
aa=impNode.reset_index(drop=True)
bb=impSP.reset_index(drop=True)
cc=impRch.reset_index(drop=True)
dd=pd.concat([aa,bb,cc], axis=1, ignore_index=True)
dd.to_csv('rechargevE.csv', index=False, header=False)
dd

             0    1             2
0        26864    1  8.221680e-05
1        26864    2  8.221680e-05
2        26864    3  1.833310e-05
3        26864    4  4.367063e-04
4        26864    5  2.055118e-05
...        ...  ...           ...
1871278  44482  153  7.994560e-06
1871279  44482  154  1.828401e-05
1871280  44482  155  5.816610e-07
1871281  44482  156  3.002406e-06
1871282  44482  157  4.529570e-06

[1871283 rows x 3 columns]

In [21]:
len(impRch)

1871283

In [22]:
len(impSP)

1871283