In [1]:
#Script for generating Recharge CSV for direct import into Vistas; outputs CSV with columns: node/SP/recharge value (ft/d)

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import numpy as np

In [5]:
#Specify recharged coefficients for each recharge zone
zone1=[0.01, 0.03]
zone2=[0.005, 0.01]
zone3=[0.01, 0.025]
zone4=[0.01, 0.2]
zone5=[0.001, 0.03]
zone6=[0.01, 0.15]

In [6]:
flow=pd.read_csv('Blancoflow.csv')
#import Blanco river flow (monthly average) in units of ft3/s; CSV must have 3 columns: Date/SP/BLAflow

In [7]:
flow

       Date   SP    BLAflow
0        SS    1  58.316667
1     8-Jan    2  58.316667
2     8-Feb    3  53.265517
3     8-Mar    4  49.470968
4     8-Apr    5  38.993333
..      ...  ...        ...
152  20-Aug  153  21.287097
153  20-Sep  154  32.906667
154  20-Oct  155  20.258065
155  20-Nov  156  15.866667
156  20-Dec  157  13.993548

[157 rows x 3 columns]

In [8]:
ppt=pd.read_csv('PRISM_ft-d.csv')
pptx=ppt.set_index('GridID')
pptx
#import PRISM precipitation data (monthly) in units of ft/d; creat df "pptx" with GridID specified as index; 1st CSV column must have prism GRIDID; than each subsequent column recharge values for each stress period

,SP1,SP2,SP3,SP4,SP5,SP6,SP7,SP8,SP9,SP10,...,SP148,SP149,SP150,SP151,SP152,SP153,SP154,SP155,SP156,SP157
GridID,,,,,,,,,,,,,,,,,,,,,
648347,0.000784,0.000784,0.000186,0.006980,0.005490,0.010134,1.300525e-03,0.001372,0.005234,0.000207,...,0.011042,0.010948,0.011477,0.003282,0.002304,0.004107,0.012321,0.000705,0.001752,0.002237
649751,0.000889,0.000889,0.000206,0.007619,0.008052,0.009981,9.768150e-04,0.001623,0.005896,0.000197,...,0.010165,0.010073,0.011451,0.003248,0.002212,0.003592,0.014469,0.000662,0.001631,0.002111
649752,0.001015,0.001015,0.000201,0.008484,0.007803,0.010547,1.053806e-03,0.001532,0.005705,0.000173,...,0.009846,0.010765,0.010955,0.002918,0.001726,0.003885,0.012542,0.000614,0.001597,0.002076
649753,0.001357,0.001357,0.000233,0.009461,0.007663,0.011684,1.205271e-03,0.001712,0.005871,0.000490,...,0.009393,0.011902,0.010421,0.002964,0.001689,0.004033,0.012859,0.000642,0.001694,0.002802
651154,0.000863,0.000863,0.000242,0.007317,0.010014,0.009142,9.190730e-04,0.002784,0.005855,0.000081,...,0.011119,0.009639,0.015455,0.004028,0.000855,0.003859,0.019051,0.000959,0.001837,0.002536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689093,0.001861,0.001861,0.000783,0.004086,0.005840,0.002677,2.723100e-05,0.011798,0.014021,0.002285,...,0.006320,0.007895,0.015758,0.003261,0.001498,0.004258,0.010717,0.000266,0.004236,0.002215
689094,0.002098,0.002098,0.000910,0.004648,0.005316,0.002133,1.093610e-07,0.010358,0.013097,0.002235,...,0.007279,0.007864,0.015394,0.003129,0.001669,0.003290,0.010787,0.000293,0.004296,0.002032
689095,0.002350,0.002350,0.001008,0.005045,0.005569,0.002555,0.000000e+00,0.010387,0.015866,0.002266,...,0.007950,0.007712,0.015985,0.002262,0.001872,0.002621,0.010480,0.000270,0.004165,0.002154
690498,0.001930,0.001930,0.000732,0.004632,0.005806,0.003097,1.161420e-04,0.010432,0.014956,0.001367,...,0.007032,0.007374,0.016709,0.003233,0.002027,0.004148,0.010063,0.000264,0.004638,0.002019
690499,0.002135,0.002135,0.000743,0.005272,0.005443,0.002537,2.482500e-05,0.011162,0.014792,0.001767,...,0.007831,0.007236,0.015513,0.002815,0.001807,0.003666,0.011317,0.000244,0.004621,0.001920

In [9]:
nodes=pd.read_csv('Rechargedomain_spatialjoin.csv')
#import table containing entries for every recharge node within the recharge domain and fields for recharge zone and PRISM gridID
#TODO: generalize table format to allow python to pull data based on column name regardless of location

In [10]:
nodes['GridID']=nodes['GridID'].apply(np.int64)
nodes.set_index('GridID')
nodes

       OBJECTID  Join_Count  TARGET_FID  row  column_    node  GridID  Rchzone
0             1           1       26285  165       58  147208  668016        2
1             2           1       23682  153      155  144605  670833        5
2             3           2       25235  160      133  146158  669426        1
3             4           1       24976  159       99  145899  669424        4
4             5           1       15415  115      137  136037  666618        3
...         ...         ...         ...  ...      ...     ...     ...      ...
10645     10646           2       33063  195       87  153987  670827        6
10646     10647           1       31306  187      129  152229  672235        5
10647     10648           1       37678  218       47  159122  672228        2
10648     10649           1       19562  135       85  140485  666613        3
10649     10650           1       29521  179      144  150444  672236        5

[10650 rows x 8 columns]

In [11]:
a=len(flow)
b=a-1
#defines array with number of stress periods from blanco river flow array

In [12]:
d=np.arange(1,a+1)
#create increasing integer array with entry for each stress period

In [13]:
c=len(nodes.node)
#defines array with number of nodes in recharge domain

In [14]:
x=nodes.set_index('GridID')
df1=x
df2=pptx
df3=pd.merge(df1,df2,left_index=True,right_index=True)
#Merge ppt and nodes dataset into new dataset called 'df3'
#for df3.iloc[:,7] now need to apply conditions to created 
    #if flow.BLAflow[0] > 40

In [15]:
#for loop apply recharge coefficients to recharge dataframe; 
for i in flow.index:
    for j in range(len(df3)):
        if df3.Rchzone.iloc[j] == 2:   
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone2[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone2[0]
        if df3.Rchzone.iloc[j] == 1:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone1[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone1[0]
        if df3.Rchzone.iloc[j] == 3:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone3[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone3[0]
        if df3.Rchzone.iloc[j] == 5:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone5[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone5[0]     
        if df3.Rchzone.iloc[j] == 6:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone6[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone6[0]  
        if df3.Rchzone.iloc[j] == 4:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone4[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*zone4[0]

In [16]:
df3

,OBJECTID,Join_Count,TARGET_FID,row,column_,node,Rchzone,SP1,SP2,SP3,...,SP148,SP149,SP150,SP151,SP152,SP153,SP154,SP155,SP156,SP157
GridID,,,,,,,,,,,,,,,,,,,,,
665209,376,1,17546,126,94,138469,3,0.000041,0.000041,0.000009,...,0.000064,0.000114,0.000374,0.000088,1.125434e-05,0.000036,0.000199,6.720430e-06,0.000033,0.000036
665209,414,1,17990,128,88,138913,3,0.000041,0.000041,0.000009,...,0.000064,0.000114,0.000374,0.000088,1.125434e-05,0.000036,0.000199,6.720430e-06,0.000033,0.000036
665209,661,1,17327,125,90,138240,3,0.000041,0.000041,0.000009,...,0.000064,0.000114,0.000374,0.000088,1.125434e-05,0.000036,0.000199,6.720430e-06,0.000033,0.000036
665209,974,1,16902,123,93,137793,3,0.000041,0.000041,0.000009,...,0.000064,0.000114,0.000374,0.000088,1.125434e-05,0.000036,0.000199,6.720430e-06,0.000033,0.000036
665209,1052,1,17115,124,92,138017,3,0.000041,0.000041,0.000009,...,0.000064,0.000114,0.000374,0.000088,1.125434e-05,0.000036,0.000199,6.720430e-06,0.000033,0.000036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675045,981,1,36058,209,136,157186,5,0.000068,0.000068,0.000024,...,0.000007,0.000011,0.000786,0.000087,7.249600e-07,0.000005,0.000020,4.224880e-07,0.000003,0.000003
675045,2230,1,36057,209,135,157185,5,0.000068,0.000068,0.000024,...,0.000007,0.000011,0.000786,0.000087,7.249600e-07,0.000005,0.000020,4.224880e-07,0.000003,0.000003
675045,2945,1,36449,211,135,157635,5,0.000068,0.000068,0.000024,...,0.000007,0.000011,0.000786,0.000087,7.249600e-07,0.000005,0.000020,4.224880e-07,0.000003,0.000003
675045,3659,1,35860,208,137,156962,5,0.000068,0.000068,0.000024,...,0.000007,0.000011,0.000786,0.000087,7.249600e-07,0.000005,0.000020,4.224880e-07,0.000003,0.000003
675045,5669,1,36254,210,135,157410,5,0.000068,0.000068,0.000024,...,0.000007,0.000011,0.000786,0.000087,7.249600e-07,0.000005,0.000020,4.224880e-07,0.000003,0.000003

In [17]:
a=df3.iloc[0,7:7+len(flow)]
a
#b=df3.iloc[:,8]
#pd.concat([a,b])

SP1      0.000041
SP2      0.000041
SP3      0.000009
SP4      0.000218
SP5      0.000041
           ...
SP153    0.000036
SP154    0.000199
SP155    0.000007
SP156    0.000033
SP157    0.000036
Name: 665209, Length: 157, dtype: float64

In [18]:
#Build new dataframe for final vistas import with 3 columns: node/SP/recharge
#dfimp=pd.DataFrame()
impNode=df3['node'].repeat(len(flow))
impSP=flow['SP']
impSP=pd.concat([impSP]*len(df3))
#Build Recharge column using concat
impRch=df3.iloc[0,7:7+len(flow)]
for i in range((len(df3)-1)):
    impRch=pd.concat([impRch,df3.iloc[i+1,7:7+len(flow)]])

#imprch=

In [19]:
impRch

SP1      4.110840e-05
SP2      4.110840e-05
SP3      9.166550e-06
SP4      2.183531e-04
SP5      4.110236e-05
             ...
SP153    5.247862e-06
SP154    2.035750e-05
SP155    4.224880e-07
SP156    2.782262e-06
SP157    3.259567e-06
Length: 1672050, dtype: float64

In [20]:
#aa=pd.concat([impNode,impSP,impRch],axis=1,ignore_index=True)
#aa=([impNode,impSP,impRch])
aa=impNode.reset_index(drop=True)
bb=impSP.reset_index(drop=True)
cc=impRch.reset_index(drop=True)
dd=pd.concat([aa,bb,cc], axis=1, ignore_index=True)
dd.to_csv('rechargevd.csv', index=False)
dd

              0    1             2
0        138469    1  4.110840e-05
1        138469    2  4.110840e-05
2        138469    3  9.166550e-06
3        138469    4  2.183531e-04
4        138469    5  4.110236e-05
...         ...  ...           ...
1672045  157410  153  5.247862e-06
1672046  157410  154  2.035750e-05
1672047  157410  155  4.224880e-07
1672048  157410  156  2.782262e-06
1672049  157410  157  3.259567e-06

[1672050 rows x 3 columns]

In [21]:
len(impRch)

1672050

In [22]:
len(impSP)

1672050