In [ ]:
#Script for generating Recharg CSV for direct import into Vistas; outputs CSV with columns: node/SP/recharge value (ft/d)
#
#To do: generalize code to allow user to input desired recharge coefficients during data import process

In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
import numpy as np

In [12]:
#Specify resired recharged coefficients for each recharge zone
Bladwn=[0.01, 0.15]
Blaup=[0.01, 0.025]
Onion=[0.01, 0.05]
Downgrad=[0.01, 0.025]

In [13]:
flow=pd.read_csv('Blancoflow_DOR.csv')
#import Blanco river flow (monthly average) in units of ft3/s; CSV must have 3 columns: Date/SP/BLAflow

In [14]:
ppt=pd.read_csv('PRISM_DOR_ft-d.csv')
pptx=ppt.set_index('GridID')
pptx
#import PRISM precipitation data (monthly) in units of ft/d; creat df "pptx" with GridID specified as index; 1st CSV column must have prism GRIDID; than each subsequent column recharge values for each stress period

,1,2,3,4,5,6,7,8,9,10,...,109,110,111,112,113,114,115,116,117,118
GridID,,,,,,,,,,,,,,,,,,,,,
648346,0.008312,0.002351,0.001077,0.005583,0.005246,0.001295,0.006759,0.002512,0.010176,0.009532,...,0.001262,0.000881,0.004000,0.006153,0.005488,0.002416,0.005767,0.008272,0.026407,0.017377
648347,0.008287,0.002330,0.001043,0.005516,0.005059,0.001445,0.006746,0.002599,0.010572,0.009673,...,0.001541,0.000827,0.004193,0.006763,0.005517,0.002611,0.005929,0.008420,0.027325,0.017668
648348,0.008354,0.002342,0.001012,0.005528,0.004923,0.001487,0.006670,0.002717,0.010920,0.009988,...,0.001553,0.000774,0.004134,0.006956,0.005746,0.002740,0.006040,0.008519,0.028316,0.017699
649749,0.008255,0.002347,0.001033,0.005603,0.005384,0.001102,0.006661,0.002394,0.009287,0.009269,...,0.000644,0.000950,0.003850,0.005515,0.005743,0.002245,0.005631,0.007772,0.024765,0.015691
649750,0.007931,0.002293,0.000988,0.005542,0.005455,0.001046,0.006708,0.002415,0.009557,0.009289,...,0.000912,0.000925,0.003863,0.005809,0.005748,0.002280,0.005678,0.008032,0.025645,0.016903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690498,0.011196,0.000695,0.001089,0.004691,0.004989,0.002085,0.007853,0.002056,0.004277,0.007060,...,0.005310,0.003212,0.004301,0.003647,0.006359,0.001245,0.007553,0.009703,0.025208,0.018106
690499,0.011260,0.000706,0.001056,0.004736,0.005030,0.002224,0.007896,0.002064,0.004276,0.007667,...,0.005360,0.003243,0.004394,0.003659,0.006398,0.001257,0.007543,0.009923,0.025254,0.018048
690500,0.011250,0.000758,0.001006,0.004735,0.005088,0.002367,0.007929,0.002053,0.004321,0.008156,...,0.005416,0.003257,0.004469,0.003679,0.006469,0.001275,0.007564,0.010227,0.025443,0.017865
691903,0.010856,0.000844,0.001104,0.004691,0.004883,0.002183,0.007804,0.002047,0.004312,0.007328,...,0.005534,0.003543,0.004532,0.003483,0.006199,0.001229,0.007319,0.009842,0.025280,0.017779
691904,0.011095,0.000860,0.001065,0.004725,0.004890,0.002291,0.007821,0.002008,0.004265,0.007967,...,0.005525,0.003478,0.004507,0.003509,0.006278,0.001246,0.007342,0.009979,0.025179,0.017809

In [15]:
nodes=pd.read_csv('Rechargedomain_spatialjoin.csv')
#import table containing entries for every recharge node within the recharge domain and fields for recharge zone and PRISM gridID
#TODO: generalize table format to allow python to pull data based on column name regardless of location

In [16]:
nodes['GridID']=nodes['GridID'].apply(np.int64)
nodes.set_index('GridID')
nodes

       OBJECTID  Join_Count  TARGET_FID  row  column_   node  GridID  Rchzone
0             1           1           0  107      110  23960  665211        3
1             2           1           1  107      112  23962  665211        3
2             3           1           2  107      113  23963  665211        3
3             4           1           3  107      114  23964  665211        3
4             5           1           4  107      115  23965  665211        3
...         ...         ...         ...  ...      ...    ...     ...      ...
10349     10350           1       10349  227       63  50913  673634        1
10350     10351           1       10350  227       64  50914  673634        1
10351     10352           1       10351  227       65  50915  673634        1
10352     10353           1       10352  228       63  51138  673634        1
10353     10354           1       10353  228       64  51139  673634        1

[10354 rows x 8 columns]

In [17]:
a=len(flow)
b=a-1
#defines array with number of stress periods from blanco river flow array

In [18]:
d=np.arange(1,a+1)
#create increasing integer array with entry for each stress period

In [19]:
c=len(nodes.node)
#defines array with number of nodes in recharge domain

In [20]:
x=nodes.set_index('GridID')
df1=x
df2=pptx
df3=pd.merge(df1,df2,left_index=True,right_index=True)
#Merge ppt and nodes dataset into new dataset called 'df3'
#for df3.iloc[:,7] now need to apply conditions to created 
    #if flow.BLAflow[0] > 40

In [21]:
#for loop apply recharge coefficients to recharge dataframe; to do: turn recharge coefficients into separate input variables at beginning of script
for i in flow.index:
    for j in range(len(df3)):
        if df3.Rchzone.iloc[j] == 2:   
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*Blaup[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*Blaup[0]
        if df3.Rchzone.iloc[j] == 1:
            if flow.BLAflow[i] > 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*Bladwn[1]
            elif flow.BLAflow[i] < 40:
                df3.iloc[j,i+7]=df3.iloc[j,i+7]*Bladwn[0]
        if df3.Rchzone.iloc[j] == 3:
                    if flow.BLAflow[i] > 40:
                        df3.iloc[j,i+7]=df3.iloc[j,i+7]*Onion[1]
                    elif flow.BLAflow[i] < 40:
                        df3.iloc[j,i+7]=df3.iloc[j,i+7]*Onion[0]
        if df3.Rchzone.iloc[j] == 5:
                    if flow.BLAflow[i] > 40:
                        df3.iloc[j,i+7]=df3.iloc[j,i+7]*Downgrad[1]
                    elif flow.BLAflow[i] < 40:
                        df3.iloc[j,i+7]=df3.iloc[j,i+7]*Downgrad[0]

In [22]:
a=df3.iloc[0,7:125]
a
#b=df3.iloc[:,8]
#pd.concat([a,b])

1      0.000108
2      0.000012
3      0.000008
4      0.000052
5      0.000045
         ...
114    0.000020
115    0.000065
116    0.000542
117    0.001781
118    0.001018
Name: 665208, Length: 118, dtype: float64

In [23]:
#Build new dataframe for final vistas import with 3 columns: node/SP/recharge
#dfimp=pd.DataFrame()
impNode=df3['node'].repeat(len(flow))
impSP=flow['SP']
impSP=pd.concat([impSP]*len(df3))
#Build Recharge column using concat
impRch=df3.iloc[0,7:125]
for i in range((len(df3)-1)):
    impRch=pd.concat([impRch,df3.iloc[i+1,7:125]])

#imprch=

In [24]:
impRch

1      0.000108
2      0.000012
3      0.000008
4      0.000052
5      0.000045
         ...
114    0.000016
115    0.000078
116    0.000284
117    0.000777
118    0.000463
Length: 1221772, dtype: float64

In [25]:
#aa=pd.concat([impNode,impSP,impRch],axis=1,ignore_index=True)
#aa=([impNode,impSP,impRch])
aa=impNode.reset_index(drop=True)
bb=impSP.reset_index(drop=True)
cc=impRch.reset_index(drop=True)
dd=pd.concat([aa,bb,cc], axis=1, ignore_index=True)
dd.to_csv('test.csv', index=False)
dd

             0    1         2
0        29109    1  0.000108
1        29109    2  0.000012
2        29109    3  0.000008
3        29109    4  0.000052
4        29109    5  0.000045
...        ...  ...       ...
1221767  47384  114  0.000016
1221768  47384  115  0.000078
1221769  47384  116  0.000284
1221770  47384  117  0.000777
1221771  47384  118  0.000463

[1221772 rows x 3 columns]